name: soda

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ master, runner ]
    paths: [ '**soda.yml' ]
  pull_request:
    branches: [ master, runner ]
    paths: [ '**soda.yml' ]
  workflow_dispatch:

jobs:
  build-soda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt install -y pcregrep patchelf git
          git clone https://github.com/FyreX-opensource-design/WINE-runners-appimage.git build && cd build
          wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/Continuous/appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage" -O appimage-builder
          chmod +x appimage-builder
          ./appimage-builder --appimage-extract
          rm appimage-builder
          mv squashfs-root appimage-builder

      - name: Get Wine Version
        id: version
        run: |
          chmod +x fetch.sh
          version_wine="$(./fetch.sh soda --version)"
          echo "version_wine=$version_wine" >> $GITHUB_ENV
          echo "version_wine=$version_wine" >> $GITHUB_OUTPUT

      - name: Build AppImage
        run: |
          mkdir dist
          cd build
          sed -i 's/BOTTLES_RUNNER/soda/' ../wine-bottles.yml
          ./appimage-builder/AppRun --recipe ../wine-bottles.yml
          mv *.AppImage ../dist/wine-soda-${{ env.version_wine }}-continuous-x86_64.AppImage
          cd .. && rm -rf build

      - name: Build Glibc-i686 AppImage
        run: |
          git clone https://github.com/ruanformigoni/wine.git build && cd build
          chmod +x fetch.sh && ./fetch.sh "soda"
          ../patch.sh ../dist/wine-soda-${{ env.version_wine }}-continuous-x86_64.AppImage
          mv *.AppImage ../dist/wine-soda-${{ env.version_wine }}-continuous-x86_64-portable-glibc-i386.AppImage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-soda
          path: dist/

    outputs:
      version: ${{ steps.version.outputs.version_wine }}

  release-soda:
    permissions: write-all
    needs: [build-soda]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wine-soda
          path: wine-soda/

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Continuous soda ${{ needs.build-soda.outputs.version }}"
          automatic_release_tag: continuous-soda
          prerelease: false
          draft: false
          files: wine-soda/*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
